version: 2.1
orbs:
  win: circleci/windows@4.1.1

jobs:
  build_windows:
    executor:
      name: win/server-2022
      shell: powershell.exe
    steps:
      - run: systeminfo
      - run:
          name: "Install CMake, Flex and Bison"
          command: |
            $machinePath = [Environment]::GetEnvironmentVariable('Path', 'MACHINE')
            $newMachineEnvironmentPath = $machinePath

            # install chocolatey
            $chocolateyPath = "$env:AllUsersProfile\chocolatey\bin"
            if(Get-Command "choco" -ErrorAction SilentlyContinue)
            {
              echo "Chocolatey is already installed. Skipping installation."
            }
            else
            {
              echo "Chocolatey net present. Installing chocolatey."
              Invoke-Expression ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
              {
                echo "Adding $chocolateyPath to Path environment variable"
                $env:Path += ";$chocolateyPath"
                $newMachineEnvironmentPath += ";$chocolateyPath"
              }
              else
              {
                echo "$chocolateyPath already present in Path environment variable"
              }
            }

            # install cmake
            $cmakePath = "${env:ProgramFiles(x86)}\CMake\bin"
            if(Get-Command "cmake" -ErrorAction SilentlyContinue)
            {
              echo "Cmake is already installed. Skipping installation."
            }
            else
            {
              echo "Cmake not present. Installing cmake."
              choco install cmake.portable -y

              if (-not ($machinePath.ToLower().Contains($cmakePath.ToLower())))
              {
                echo "Adding $cmakePath to Path environment variable"
                $env:Path += ";$cmakePath"
                $newMachineEnvironmentPath = "$cmakePath;$newMachineEnvironmentPath"
              }
              else
              {
                echo "$cmakePath already present in Path environment variable"
              }
            }

            # install winflexbison3
            $winflexbison3Path = "${env:ProgramFiles(x86)}\WinFlexBison\bin"
            if(Get-Command "bison" -ErrorAction SilentlyContinue)
            {
              echo "bison is already installed. Skipping installation."
            }
            else
            {
              echo "bison not present. Installing bison."
              choco install winflexbison3 -y

              if (-not ($machinePath.ToLower().Contains($winflexbison3Path.ToLower())))
              {
                echo "Adding $winflexbison3Path to Path environment variable"
                $env:Path += ";$winflexbison3Path"
                $newMachineEnvironmentPath = "$winflexbison3Path;$newMachineEnvironmentPath"
              }
              else
              {
                echo "$winflexbison3Path already present in Path environment variable"
              }
            }

            # update machine environment path
            if ($newMachineEnvironmentPath -ne $machinePath)
            {
              [Environment]::SetEnvironmentVariable('Path', $newMachineEnvironmentPath, 'MACHINE')
            }
      - restore_cache:
          keys:
            - source-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - source-{{ arch }}-{{ .Branch }}-
            - source-{{ arch }}-
      - run:
          name: restore repo
          command: |
            if (Test-Path -Path ".git" ) {
              git restore .
            }
      - checkout
      - run:
          name: init submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: git gc
          command: |
            git gc
            git lfs prune
      - save_cache:
          key: source-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: "Build Dependencies"
          command: |
            scripts/build_imgui
            scripts/build_crossguid
            scripts/build_opengex
            scripts/build_zlib
            scripts/build_bullet
            scripts/build_glslangValidator
            scripts/build_spirvcross
            scripts/build_libispc-texcomp
      - run:
          name: "Build Engine"
          command: |
            scripts/build
      - run:
          name: "Cook Asset"
          command: |
            scripts/cook_material
      - run:
          name: "Test"
          command: |
            cmake --build build --target RUN_TESTS
      - run:
          name: Package
          command: |
            cmake --build ./build --target package
      - persist_to_workspace:
          root: build
          paths:
            - GEFS-0.1.0-win64.exe
      - store_artifacts:
          path: build/GEFS-0.1.0-win64.exe
  build_linux:
    #docker:
    #  - image: ubuntu:20.04
    #resource_class: xlarge
    machine:
      image: ubuntu-2204:2022.04.1 # recommended linux image
    resource_class: large
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt update 
            sudo apt install -y curl clang cmake ninja-build git uuid-dev 
            sudo apt install -y libx11-dev libx11-xcb-dev libgl1-mesa-dev libnss3-dev libxss-dev libatk1.0-dev libatk-bridge2.0-dev libglib2.0-dev libpango1.0-dev libxi-dev libfontconfig1-dev libnspr4-dev libxcomposite-dev libxcursor-dev libxrender-dev libxtst-dev libxrandr-dev libgio2.0-cil-dev libdbus-1-dev libasound2-dev libcups2-dev libncurses5-dev
            sudo apt install -y flex bison
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt install -y git-lfs
          environment:
            DEBIAN_FRONTEND: noninteractive
      - restore_cache:
          keys:
            - source-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - source-{{ arch }}-{{ .Branch }}-
            - source-{{ arch }}-
      - run:
          name: restore repo
          command: |
            if [ -d ".git" ]; then
              git restore .
            fi
      - checkout
      - run:
          name: init submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: git gc
          command: |
            git gc
            git lfs prune
      - save_cache:
          key: source-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: "Build Dependencies"
          command: |
            ./scripts/build_imgui.sh
            ./scripts/build_crossguid.sh
            ./scripts/build_opengex.sh
            ./scripts/build_bullet.sh
            ./scripts/build_glslangValidator.sh
            ./scripts/build_spirvcross.sh
            ./scripts/build_libispc-texcomp.sh
      - run:
          name: "Build Engine"
          command: |
            ./scripts/build-ninja.sh
      - run:
          name: "Cook Asset"
          command: |
            scripts/cook_material.sh
      - run:
          name: Test
          command: |
            cmake --build ./build --target test
      - run:
          name: Package
          command: |
            cmake --build ./build --target package
      - persist_to_workspace:
          root: build
          paths:
            - GEFS-0.1.0-Linux.sh
            - GEFS-0.1.0-Linux.tar.gz
            - GEFS-0.1.0-Linux.tar.Z
      - store_artifacts:
          path: build/GEFS-0.1.0-Linux.sh
      - store_artifacts:
          path: build/GEFS-0.1.0-Linux.tar.gz
      - store_artifacts:
          path: build/GEFS-0.1.0-Linux.tar.Z
  build_macos:
    macos:
      xcode: "13.4.0"
    steps:
      - restore_cache:
          keys:
            - source-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - source-{{ arch }}-{{ .Branch }}-
            - source-{{ arch }}-
      - run:
          name: restore repo
          command: |
            if [ -d ".git" ]; then
              git restore .
            fi
      - checkout
      - run:
          name: init submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: git gc
          command: |
            git gc
            git lfs prune
      - save_cache:
          key: source-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Install Dependencies via MacPorts
          command: |
            curl -L -o $(pwd)/MacPorts-2.7.2-12-Monterey.pkg https://github.com/macports/macports-base/releases/download/v2.7.2/MacPorts-2.7.2-12-Monterey.pkg
            sudo installer -package $(pwd)/MacPorts-2.7.2-12-Monterey.pkg -target /
            rm $(pwd)/MacPorts-2.7.2-12-Monterey.pkg
            export PATH=/opt/local/bin:/opt/local/sbin:$PATH 
            sudo -E port -q install cmake ninja flex bison
      - run:
          name: "Build Dependencies"
          command: |
            export PATH=/opt/local/bin:/opt/local/sbin:$PATH 
            ./scripts/build_imgui.sh
            ./scripts/build_crossguid.sh
            ./scripts/build_opengex.sh
            ./scripts/build_zlib.sh
            ./scripts/build_bullet.sh
            ./scripts/build_glslangValidator.sh
            ./scripts/build_spirvcross.sh
            ./scripts/build_libispc-texcomp.sh
      - run:
          name: "Build Engine"
          command: |
            export PATH=/opt/local/bin:/opt/local/sbin:$PATH 
            ./scripts/build-ninja.sh
      - run:
          name: "Cook Asset"
          command: |
            scripts/cook_material.sh
      - run:
          name: Test
          command: |
            export PATH=/opt/local/bin:/opt/local/sbin:$PATH 
            cmake --build ./build --target test
      - run:
          name: Package
          command: |
            export PATH=/opt/local/bin:/opt/local/sbin:$PATH 
            cmake --build ./build --target package
      - persist_to_workspace:
          root: build
          paths:
            - GEFS-0.1.0-Darwin.sh
            - GEFS-0.1.0-Darwin.tar.gz
      - store_artifacts:
          path: build/GEFS-0.1.0-Darwin.sh
      - store_artifacts:
          path: build/GEFS-0.1.0-Darwin.tar.gz
  build_android:
    working_directory: ~/project
    docker:
      - image: tim03/android-sdk-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt install -y git-lfs
      - restore_cache:
          keys:
            - source-android-{{ .Branch }}-{{ .Revision }}
            - source-android-{{ .Branch }}-
            - source-android-
      - run:
          name: restore repo
          command: |
            if [ -d ".git" ]; then
              git restore .
            fi
      - checkout
      - run:
          name: init submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: git gc
          command: |
            git gc
            git lfs prune
      - save_cache:
          key: source-android-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          key: jars-{{ checksum "Game/Billiard/build.gradle" }}-{{
            checksum  "Game/Billiard/app/build.gradle" }}
      - run:
          name: Setup Emulator
          command: |
            sdkmanager "system-images;android-24;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
          working_directory: Game/Billiard
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
          working_directory: Game/Billiard
      - save_cache:
          paths:
            - Game/Billiard/.gradle
          key: jars-{{ checksum "Game/Billiard/build.gradle" }}-{{
            checksum  "Game/Billiard/app/build.gradle" }}
      - run:
          name: Build External Dependencies
          command: |
            ./scripts/build_crossguid-android.sh
            ./scripts/build_opengex-android.sh
            ./scripts/build_bullet-android.sh
      - run:
          name: Build
          command: |
            ./gradlew build
          working_directory: Game/Billiard
      - run:
          name: Launch Emulator
          command: |
            emulator @test -no-audio -no-window -no-boot-anim -accel on
          background: true
          working_directory: Game/Billiard
      - run:
          name: Deploy Assets
          command: |
            adb wait-for-device
            adb push ../../Asset/Scene/Example.ogex /data/local/tmp/Scene/Example.ogex
            adb push ../../Asset/Scene/splash.ogex /data/local/tmp/Scene/splash.ogex
            adb push ../../Asset/Textures/huff_simple0.jpg /data/local/tmp/Textures/huff_simple0.jpg
            adb push ../../Asset/Textures/eye.png /data/local/tmp/Textures/eye.png
            adb push ../../Asset/Textures/interior_lod0.tga /data/local/tmp/Textures/interior_lod0.tga
          working_directory: Game/Billiard
      - run:
          name: Run Geom Math Library Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/GeomMathTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/GeomMathTest
            adb shell "cd /data/local/tmp && ./GeomMathTest"
          working_directory: Game/Billiard
      - run:
          name: Run Color Space Conversion Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/ColorSpaceConversionTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/ColorSpaceConversionTest
            adb shell "cd /data/local/tmp && ./ColorSpaceConversionTest"
          working_directory: Game/Billiard
      - run:
          name: Run Asset Loader Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/AssetLoaderTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/AssetLoaderTest
            adb shell "cd /data/local/tmp && ./AssetLoaderTest"
          working_directory: Game/Billiard
      - run:
          name: Run JPEG decoder Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/JpegParserTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/JpegParserTest
            adb shell "cd /data/local/tmp && ./JpegParserTest"
          working_directory: Game/Billiard
      - run:
          name: Run PNG decoder Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/PngParserTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/PngParserTest
            adb shell "cd /data/local/tmp && ./PngParserTest"
          working_directory: Game/Billiard
      - run:
          name: Run OGEX parser Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/OgexParserTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/OgexParserTest
            adb shell "cd /data/local/tmp && ./OgexParserTest"
          working_directory: Game/Billiard
      - run:
          name: Run Scene Loading Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/SceneLoadingTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/SceneLoadingTest
            adb shell "cd /data/local/tmp && ./SceneLoadingTest"
          working_directory: Game/Billiard
      - run:
          name: Run Bullet Test
          command: |
            adb push app/build/intermediates/cmake/debug/obj/armeabi-v7a/BulletTest /data/local/tmp/
            adb shell chmod +x /data/local/tmp/BulletTest
            adb shell "cd /data/local/tmp && ./BulletTest"
          working_directory: Game/Billiard
      - store_artifacts:
          path: Game/Billiard/app/build/reports
          destination: reports
      - store_artifacts:
          path: Game/Billiard/app/build/test-results
          destination: test-results
      - store_artifacts:
          path: Game/Billiard/app/build/outputs/apk
          destination: apk
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
  publish_github_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.1.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build-and-test: #for branch
    jobs:
      # - build_windows
      - build_linux
      - build_macos
  build-and-test-and-release: #for tags
    jobs:
      - build_windows:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - build_linux:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - build_macos:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish_github_release:
          requires:
            - build_linux
            - build_macos
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
